---

name: stolon
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: stolon
  version: latest
- name: consul
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.227.0/24
    reserved: [10.244.227.1]
    static: &cips
    - 10.244.227.201
    - 10.244.227.202
    - 10.244.227.203

properties:
  consul:
    server: false
    join_hosts: *cips

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2
  resource_pool: default
  networks:
   - name: default

jobs:
- name: consul
  resource_pool: default
  templates:
  - name: consul
    release: consul
  networks:
  - name: default
    static_ips: *cips
  instances: 3
  properties:
    consul:
      server: true

- name: proxy
  resource_pool: default
  templates:
  - name: stolon-proxy
    release: stolon
  - name: consul
    release: consul
  networks:
  - name: default
  instances: 1

- name: sentinel
  resource_pool: default
  templates:
  - name: stolon-sentinel
    release: stolon
  - name: consul
    release: consul
  networks:
  - name: default
  instances: 2

- name: keeper
  resource_pool: default
  templates:
  - name: consul
    release: consul
  - name: stolon-keeper
    release: stolon
  networks:
  - name: default
  instances: 3
