---
name: stolon

releases:
- name: stolon
  version: latest
- name: consul
  version: 170

instance_groups:
- name: proxy
  jobs:
  - name: stolon-proxy
    release: stolon
  - name: consul_agent
    release: consul
    consumes:
      consul_server: nil
      consul_client:
        from: ((consul_client_link_name))
        deployment: ((consul_deployment_name))
      consul_common:
        from: ((consul_common_link_name))
        deployment: ((consul_deployment_name))
  networks:
  - name: default
  instances: ((stolon_proxy_instances))
  vm_type: default
  stemcell: default
  azs: [ z1, z2, z3 ]

- name: sentinel
  jobs:
  - name: stolon-sentinel
    release: stolon
  - name: consul_agent
    release: consul
    consumes:
      consul_server: nil
      consul_client:
        from: ((consul_client_link_name))
        deployment: ((consul_deployment_name))
      consul_common:
        from: ((consul_common_link_name))
        deployment: ((consul_deployment_name))
  networks:
  - name: default
  instances: ((stolon_sentinel_instances))
  vm_type: default
  stemcell: default
  azs: [ z1, z2, z3 ]

- name: keeper
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_server: nil
      consul_client:
        from: ((consul_client_link_name))
        deployment: ((consul_deployment_name))
      consul_common:
        from: ((consul_common_link_name))
        deployment: ((consul_deployment_name))
  - name: stolon-keeper
    release: stolon
  networks:
  - name: default
  instances: ((stolon_keeper_instances))
  vm_type: default
  stemcell: default
  azs: [ z1, z2, z3 ]

properties:
  pg:
    default_lang: "en_US.utf8"

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2
  resource_pool: default
  networks:
   - name: default

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
